apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-loadbalancer-config
data:
  default.conf: |
    upstream backend {
      server nginx-page1-service:80;
      server nginx-page2-service:80;
      server nginx-page3-service:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

